services:

  kernel.listener.console:
    class:  App\ChainCommandBundle\EventListener\ChainCommandEventListener
    arguments:
      - '@chain.command.dispatcher'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

  chain.command.dispatcher:
    class: App\ChainCommandBundle\Dispatcher\ChainCommandDispatcher
    arguments: ['@chain.command.service','@logger']

  chain.command.service:
    class: App\ChainCommandBundle\Service\ChainCommandService