services:
  kernel.listener.console:
    class:  App\ChainCommandBundle\EventListener\ChainCommandEventListener
    arguments:
      - '@chain.command.dispatcher'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
      - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }

  chain.command.dispatcher:
    class: App\ChainCommandBundle\Dispatcher\ChainCommandDispatcher
    arguments: ['@chain.command.repository','@logger']

  chain.command.repository:
    class: App\ChainCommandBundle\Repository\ChainCommandRepository